Repository pda-min-ji/front, pull requests merged in 2024-11, with the labels that each got.

#18 #13 Feat : 오늘의 문제 컴포넌트 개발
  package-lock.json
  package.json
  src/App.jsx
  src/components/QuestionComponent.jsx
  src/styles/ProblemComponent.css
  vite.config.js
Labels: enhancement

#20 #19 Feat : 정답여부 확인 함수
  package-lock.json
  package.json
  src/components/ProblemComponent.jsx
  src/components/QuestionComponent.jsx
  src/components/TestComponents.jsx
  src/utils/isCorrectAnswer.js
Labels: enhancement

#21 Feat#8 로그인 및 회원가입 구현, CORS 에러 해결 및 API 요청 설정
  package-lock.json
  src/App.jsx
  src/components/LoginComponent.jsx
  src/components/SignUpComponent.jsx
  src/components/TestComponent.jsx
  src/layouts/Header.jsx
  src/lib/apis/apiClient.js
  src/lib/apis/auth.js
  src/pages/TestPages.jsx
  src/routers/TestRouters.jsx
  src/routers/mainRouter.jsx
  src/styles/LoginStyle.css
  src/styles/SignUpStyle.css
  vite.config.js
Labels: Feature

#24 #23 Fix : modify css & layout
  package-lock.json
  src/App.css
  src/App.jsx
  src/components/QuestionComponent.jsx
  src/routers/mainRouter.jsx
  src/styles/LoginStyle.css
  src/utils/isCorrectAnswer.js
Labels: bug

#26 #22 Feat : 오늘의 문제 컴포넌트 정답확인 버튼 추가 및 기능 구현
  index.html
  src/components/QuestionComponent.jsx
  src/styles/ProblemComponent.css
  src/utils/isCorrectAnswer.js
Labels: enhancement

#29 #28 Fix : App.jsx 충돌 해결
  src/App.jsx
  src/routers/mainRouter.jsx
Labels: wontfix

#32 Feat#11 유저 프로필 페이지 생성
  src/App.css
  src/App.jsx
  src/components/LoginComponent.jsx
  src/components/UserProfile.jsx
  src/components/UserProfileComponent.jsx
  src/contexts/userContext.jsx
  src/layouts/Header.jsx
  src/routers/mainRouter.jsx
  src/styles/LoginStyle.css
  src/styles/RankingStyle.css
Labels: Feature
